### PR TITLE
Scalafmt version bump from 2.2.2 to 2.3.2

### PR DESCRIPTION
**Pull request by AndriusFromLTU**

### CODE REVIEW

**Comment by mroth** [comment]
Huh, does GitHub Actions not run on outside PRs? Let me look into this and report back... (I can run locally manually if not.)

_(Btw, for a full production release, we also will need to update the version of scalafmt for the Mac/Linux binaries, which is in `.github/workflows/build.yml`, currently at line 65. I haven't figured out a way to have one place to set it for both yet.)_

**Comment by mroth** [comment]
I pushed a change in https://github.com/mroth/scalafmt-native/commit/f1b2b969a992ab37dd96ed5f79a6b388b263d7ad that I believe (hope ) will make the GitHub Actions CI run on PRs as well.  If you rebase your branch to that I think we'll see it run?

**Comment by mroth** [comment]
Interesting, on the CI it looks like these are building fine. @myDisconnect should we try to debug why it doesn't build on your machine locally first, or okay to merge this and do a release?

**Comment by AndriusFromLTU** [comment]
Merge it 👍

**Comment by mroth** [comment]
Thanks!

**Pull request merged**
